# how to:
# conda env create -f environment.yml
# source activate blockchain

name: blockchain
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter